controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# API routes are handled by Symfony controllers with /api prefix
api:
    resource: ../src/Controller/
    type: attribute
    prefix: /api
    name_prefix: api_

# React frontend routes - let the frontend handle routing
frontend:
    path: /{reactRouting}
    controller: App\Controller\FrontendController::index
    requirements:
        reactRouting: ^(?!api|_wdt|_profiler).+
    defaults:
        reactRouting: ''
