monolog:
    channels:
        - deployment
        - dropbox

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            
            # Deployment logging for development
            deployment:
                type: rotating_file
                path: "%kernel.logs_dir%/deployment/deployment.log"
                level: "%env(DEPLOY_LOG_LEVEL)%"
                max_files: 30
                channels: ["deployment"]
                formatter: monolog.formatter.json
                
            # Dropbox logging for development  
            dropbox:
                type: rotating_file
                path: "%kernel.logs_dir%/dropbox/dropbox.log"
                level: "%env(DROPBOX_LOG_LEVEL)%"
                max_files: 30
                channels: ["dropbox"]
                formatter: monolog.formatter.json
            
            # Console output for development
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages to keep in memory
                channels: ["!event"]
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 30
                
            # Production deployment logging
            deployment:
                type: rotating_file
                path: "%kernel.logs_dir%/deployment/deployment.log"
                level: "%env(DEPLOY_LOG_LEVEL)%"
                max_files: 30
                channels: ["deployment"]
                formatter: deployment_formatter
                
            # Production Dropbox logging
            dropbox:
                type: rotating_file
                path: "%kernel.logs_dir%/dropbox/dropbox.log" 
                level: "%env(DROPBOX_LOG_LEVEL)%"
                max_files: 30
                channels: ["dropbox"]
                formatter: dropbox_formatter
                
            # Deprecation warnings
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecation.log"
                channels: ["php"]

    formatters:
        # Custom formatter for deployment logs
        deployment_formatter:
            type: line
            format: "[%datetime%] %channel%.%level_name%: %message% %context% %extra%\n"
            date_format: "Y-m-d H:i:s"
            
        # Custom formatter for Dropbox logs  
        dropbox_formatter:
            type: line
            format: "[%datetime%] %channel%.%level_name%: %message% %context% %extra%\n"
            date_format: "Y-m-d H:i:s"
