/**
 * Generated by scripts/build-conversion-tools.mjs — do not edit by hand.
 *
 * Run `npm run build:tools` after changing anything in
 * scripts/comic-conversion/, and commit the result along with the zips in
 * public/tools/.
 */

export const CONVERSION_TOOLS_VERSION = "1.0.0";

export const CONVERSION_TOOLS = [
  {
    id: "windows",
    label: "Windows (PowerShell)",
    href: "/tools/convert-cbr-to-cbz-windows.zip",
    fileName: "convert-cbr-to-cbz-windows.zip",
    sha256: "5df68efd311a8078a3ac40341fba595eaa7e008484c7436ed3b6aef0518cfd3c",
    sizeBytes: 13091,
  },
  {
    id: "linux",
    label: "Linux and macOS (bash)",
    href: "/tools/convert-cbr-to-cbz-linux.zip",
    fileName: "convert-cbr-to-cbz-linux.zip",
    sha256: "04546cb65bef56e9e7b593db7c1c9d24d94cb39c3c5ad9323ca25cd7da92f0f1",
    sizeBytes: 10689,
  },
];
