name: Build and Deploy Frontend

on:
  # Only trigger on PR merges to main (not direct pushes)
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  build-and-deploy:
    # Only run when a PR to main is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
      - name: Upload build artifacts (for reference)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
          retention-days: 7
          
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # need to add these secrets to the repo
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/dist/
          server-dir: backend/public/
          # Exclude important backend files from deletion
          exclude: |
            **/.htaccess
            **/index.php
            **/error.php
            **/uploads/**
          # Use clean slate to avoid file sync issues and state file accumulation
          dangerous-clean-slate: true
